### ISSUE TITLE
4 X P40 is not enough?

### ISSUE THREAD

**Issue by PkuRainBow** [ShuLiu1993/PANet#11]
I have tried to reproduce your results with 4X P100 but meet such errors.

I am wondering whether anyone could give me some hints.

```
loss_rpn_bbox_fpn6: 0.014951
INFO train_net_step.py: 443: Save ckpt on exception ...
INFO train_net_step.py: 135: save model: Outputs/e2e_panet_R-50-FPN_2x_mask/ckpt/model_step1506.pth
INFO train_net_step.py: 445: Save ckpt done.
Traceback (most recent call last):
  File "tools/train_net_step.py", line 425, in main
    net_outputs = maskRCNN(**input_data)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/teamscratch/msravcshare/yuyua/code/segmentation/PANet/lib/nn/parallel/data_parallel.py", line 111, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/teamscratch/msravcshare/yuyua/code/segmentation/PANet/lib/nn/parallel/data_parallel.py", line 139, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/teamscratch/msravcshare/yuyua/code/segmentation/PANet/lib/nn/parallel/parallel_apply.py", line 67, in parallel_apply
    raise output
  File "/teamscratch/msravcshare/yuyua/code/segmentation/PANet/lib/nn/parallel/parallel_apply.py", line 42, in _worker
    output = module(*input, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/teamscratch/msravcshare/yuyua/code/segmentation/PANet/lib/modeling/model_builder.py", line 144, in forward
    return self._forward(data, im_info, roidb, **rpn_kwargs)
  File "/teamscratch/msravcshare/yuyua/code/segmentation/PANet/lib/modeling/model_builder.py", line 215, in _forward
    loss_mask = mask_rcnn_heads.mask_rcnn_losses(mask_pred, rpn_ret['masks_int32'])
  File "/teamscratch/msravcshare/yuyua/code/segmentation/PANet/lib/modeling/mask_rcnn_heads.py", line 101, in mask_rcnn_losses
    masks_pred.view(n_rois, -1), masks_gt, weight, size_average=False)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1651, in binary_cross_entropy_with_logits
    loss = input - input * target + max_val + ((-max_val).exp() + (-input - max_val).exp()).log()
RuntimeError: CUDA error: out of memory
```

**Comment by ShuLiu1993** [comment]
I used 8 * P40 for this experiment with 2 images on one P40. P40 is with 24GB memory compared with the 16GB memory of P100. Maybe you can use smaller image size or smaller batch size.
