### ISSUE TITLE
No module named cython_bbox

### ISSUE THREAD

**Issue by LigZhong** [ShuLiu1993/PANet#16]
I haven't encountered error running **sh make.sh**  but when I run test_net.py I still got this error below:

 'VIS': False,
 'VIS_TH': 0.9}
loading annotations into memory...
Done (t=0.66s)
creating index...
index created!
INFO subprocess.py:  87: detection range command 0: python /home/zhongligeng/projects/PANet/tools/test_net.py --range 0 834 --cfg /home/zhongligeng/projects/PANet/test/detection_range_config.yaml --set TEST.DATASETS '("coco_2017_val",)' --output_dir /home/zhongligeng/projects/PANet/test --load_ckpt /home/zhongligeng/projects/PANet/Outputs/panet_mask_step179999.pth
INFO subprocess.py:  87: detection range command 1: python /home/zhongligeng/projects/PANet/tools/test_net.py --range 834 1668 --cfg /home/zhongligeng/projects/PANet/test/detection_range_config.yaml --set TEST.DATASETS '("coco_2017_val",)' --output_dir /home/zhongligeng/projects/PANet/test --load_ckpt /home/zhongligeng/projects/PANet/Outputs/panet_mask_step179999.pth
INFO subprocess.py:  87: detection range command 2: python /home/zhongligeng/projects/PANet/tools/test_net.py --range 1668 2501 --cfg /home/zhongligeng/projects/PANet/test/detection_range_config.yaml --set TEST.DATASETS '("coco_2017_val",)' --output_dir /home/zhongligeng/projects/PANet/test --load_ckpt /home/zhongligeng/projects/PANet/Outputs/panet_mask_step179999.pth
INFO subprocess.py:  87: detection range command 3: python /home/zhongligeng/projects/PANet/tools/test_net.py --range 2501 3334 --cfg /home/zhongligeng/projects/PANet/test/detection_range_config.yaml --set TEST.DATASETS '("coco_2017_val",)' --output_dir /home/zhongligeng/projects/PANet/test --load_ckpt /home/zhongligeng/projects/PANet/Outputs/panet_mask_step179999.pth
INFO subprocess.py:  87: detection range command 4: python /home/zhongligeng/projects/PANet/tools/test_net.py --range 3334 4167 --cfg /home/zhongligeng/projects/PANet/test/detection_range_config.yaml --set TEST.DATASETS '("coco_2017_val",)' --output_dir /home/zhongligeng/projects/PANet/test --load_ckpt /home/zhongligeng/projects/PANet/Outputs/panet_mask_step179999.pth
INFO subprocess.py:  87: detection range command 5: python /home/zhongligeng/projects/PANet/tools/test_net.py --range 4167 5000 --cfg /home/zhongligeng/projects/PANet/test/detection_range_config.yaml --set TEST.DATASETS '("coco_2017_val",)' --output_dir /home/zhongligeng/projects/PANet/test --load_ckpt /home/zhongligeng/projects/PANet/Outputs/panet_mask_step179999.pth
INFO subprocess.py: 127: # ---------------------------------------------------------------------------- #
INFO subprocess.py: 129: stdout of subprocess 0 with range [1, 834]
INFO subprocess.py: 131: # ---------------------------------------------------------------------------- #
Traceback (most recent call last):
  File "/home/zhongligeng/projects/PANet/tools/test_net.py", line 14, in <module>
    from core.test_engine import run_inference
  File "/home/zhongligeng/projects/PANet/lib/core/test_engine.py", line 36, in <module>
    from core.test import im_detect_all
  File "/home/zhongligeng/projects/PANet/lib/core/test.py", line 43, in <module>
    import utils.boxes as box_utils
  File "/home/zhongligeng/projects/PANet/lib/utils/boxes.py", line 52, in <module>
    import utils.cython_bbox as cython_bbox
_ImportError: No module named cython_bbox_
Traceback (most recent call last):
  File "tools/test_net.py", line 112, in <module>
    check_expected_results=True)
  File "/home/zhongligeng/projects/PANet/lib/core/test_engine.py", line 128, in run_inference
    all_results = result_getter()
  File "/home/zhongligeng/projects/PANet/lib/core/test_engine.py", line 108, in result_getter
    multi_gpu=multi_gpu_testing
  File "/home/zhongligeng/projects/PANet/lib/core/test_engine.py", line 154, in test_net_on_dataset
    args, dataset_name, proposal_file, num_images, output_dir
  File "/home/zhongligeng/projects/PANet/lib/core/test_engine.py", line 186, in multi_gpu_test_net_on_dataset
    args.load_ckpt, args.load_detectron, opts
  File "/home/zhongligeng/projects/PANet/lib/utils/subprocess.py", line 107, in process_in_parallel
    log_subprocess_output(i, p, output_dir, tag, start, end)
  File "/home/zhongligeng/projects/PANet/lib/utils/subprocess.py", line 145, in log_subprocess_output
    assert ret == 0, 'Range subprocess failed (exit code: {})'.format(ret)
AssertionError: Range subprocess failed (exit code: 1)

Any idea how to solve this?

**Comment by shafu0x** [comment]
Hey, what operating system are you using?

**Comment by cece-jy** [comment]
I have the same problem , have you solved it ?

**Comment by harshgrovr** [comment]
cd lib  # please change to this directory
sh make.sh
