### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.cython_bbox'

### ISSUE THREAD

**Issue by manansaxena** [ShuLiu1993/PANet#43]
Traceback (most recent call last):
  File "infer_simple.py", line 28, in <module>
    from core.test import im_detect_all
  File "/content/PANet/lib/core/test.py", line 43, in <module>
    import utils.boxes as box_utils
  File "/content/PANet/lib/utils/boxes.py", line 52, in <module>
    import utils.cython_bbox as cython_bbox
ModuleNotFoundError: No module named 'utils.cython_bbox'

I am using google colab with cuda version 9.0 and pytorch version 0.4.0

**Comment by lizolson** [comment]
I think we need to cd into the lib folder and run 'bash make.sh'.
